import Head from 'next/head';

import GameShowcase from '@/root/components/GameShowcase/GameShowcase';

export default function Home() {
  return (
    <>
      <Head>
        <title>Baffle Raffle</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <GameShowcase />
      </main>
    </>
  );
}
