import Head from 'next/head'
import { signOut } from "next-auth/react";

import { trpc } from "../utils/trpc";

export default function Home() {
  const hello = trpc.example.hello.useQuery({text: "from tRPC"});

  return (
    <>
      <Head>
        <title>Baffle Raffle</title>
        <meta name="description" content="Generated by create-t3-app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main>

        <section className='mt-24'>
          <button className='text-white' onClick={() => signOut()}>sign out</button>
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
        </section>
      </main>
    </>
  )
}

