import Head from 'next/head'
import { signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";

export default function Home() {
  const {data: sessionData} = useSession();



  return (
    <>
      <Head>
        <title>Baffle Raffle</title>
        <meta name="description" content="Generated by create-t3-app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main>

        <section className='mt-24'>
          <button className='text-white' onClick={() => signOut()}>sign out</button>

        </section>
      </main>
    </>
  )
}

