import { GetServerSidePropsContext, InferGetServerSidePropsType } from 'next';
import { unstable_getServerSession } from 'next-auth';
import { signOut } from 'next-auth/react';
import Head from 'next/head';

import GameForm from '@/root/components/GameForm';

import { authOptions } from '@/root/pages/api/auth/[...nextauth]';

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const session = await unstable_getServerSession(context.req, context.res, authOptions);

  if (!session) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    };
  }

  return {
    props: {
      session,
    },
  };
}

const User = ({ session }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <>
      <Head>
        <title>Baffle Raffle | Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className="text-center text-2xl text-white">
        <span>Logged in as {session.user?.address}</span>
      </p>
      <section className="text-center text-white">
        <GameForm />

        <section className="mt-24 text-white">
          <button onClick={() => signOut()}>sign out</button>
        </section>
      </section>
    </>
  );
};

export default User;
